version: "2.0"

services:
  near:
    image: p2pstaking/near-node:shardnet-latest
    expose:
      - port: 24567
        as: 24567
        to:
          - global: true

profiles:
  compute:
    near:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          size: 80Gi
  placement:
    westcoast:
      attributes:
        host: akash
      pricing:
        near: 
          denom: uakt
          amount: 1000

deployment:
  near:
    westcoast:
      profile: near
      count: 1
