version: "2.0"

services:
  near:
    image: p2pstaking/akash:ubuntu-focal-ssh-systemd-beta0.1
    env:
      - MY_IDENTITY=ssh-ed25519 xxx.....
      - LOG_CMD=mkdir -p /root/.near/ && echo "p2pstaking/akash:ubuntu-focal-ssh-systemd-beta0.1 started" >> /root/.near/neard.err && tail -f /root/.near/neard.err
    expose:
      - port: 22
        as: 22
        to:
          - global: true
      - port: 3030
        as: 3030
        to:
          - global: true

profiles:
  compute:
    near:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - name: data
            size: 800Gi
#            attributes:
#              class: beta3
  placement:
    datacenter:
      attributes:
        host: akash
      pricing:
        near: 
          denom: uakt
          amount: 1000

deployment:
  near:
    datacenter:
      profile: near
      count: 1
