version: "2.0"

services:
  near:
    image: p2pstaking/akash:ubuntu-focal-ssh-systemd-beta0.2
    params:
      storage:
        data:
          mount: /root/.near/
    env:
      - MY_IDENTITY=ssh-ed25519 xxx.....
      - LOG_FILE=/root/.near/neard.err
    expose:
      - port: 22
        as: 22
        to:
          - global: true
      - port: 3030
        as: 3030
        to:
          - global: true
      - port: 24567
        as: 24567
        to:
          - global: true

profiles:
  compute:
    near:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - name: data
            size: 600Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    datacenter:
      attributes:
        host: akash
      pricing:
        near: 
          denom: uakt
          amount: 1000

deployment:
  near:
    datacenter:
      profile: near
      count: 1
